POST http://localhost:3000/api/orang
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzMWM3ODM3OTk4ZmYyYzhiYWIzZjhjNCIsImlhdCI6MTY2MjgxMDE5NywiZXhwIjoxNjYyODk2NTk3fQ.OVUTL5V6HY2qcYqsW7m_Kuwr-x8XVkdMIN1rzXo2VYY
Content-Type: application/json

{
    "nama" : "hasan",
    "alamat" : "bayat",
    "noHP" : "08123456782",
    "tanggal" : "2022-08-10",
    "status" : "Saudara"
}

###

GET  http://localhost:3000/api/orang
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzMWM3ODM3OTk4ZmYyYzhiYWIzZjhjNCIsImlhdCI6MTY2MjgxMDE5NywiZXhwIjoxNjYyODk2NTk3fQ.OVUTL5V6HY2qcYqsW7m_Kuwr-x8XVkdMIN1rzXo2VYY


###
GET http://localhost:3000/api/orang/631c7884998ff2c8bab3f8cf
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzMWM3ODM3OTk4ZmYyYzhiYWIzZjhjNCIsImlhdCI6MTY2MjgxMDE5NywiZXhwIjoxNjYyODk2NTk3fQ.OVUTL5V6HY2qcYqsW7m_Kuwr-x8XVkdMIN1rzXo2VYY

###
GET http://localhost:3000/api/orang/cari?src=s
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzMWFhY2NjNGVjNTIwYzhiZDhmZmJlYSIsImlhdCI6MTY2MjcyMjI4MywiZXhwIjoxNjYyODA4NjgzfQ.JioYwy-elFFnWLqLTfKKHzQtD5ItihIXy_LTysrtX10

###

PUT http://localhost:3000/api/orang/631c7884998ff2c8bab3f8cf
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzMWFhY2NjNGVjNTIwYzhiZDhmZmJlYSIsImlhdCI6MTY2MjcyNzg2NSwiZXhwIjoxNjYyODE0MjY1fQ.HSKLo7eZWWW_ZGVKkqZPCD6kgQdeocpctSwhMqw45m8
Content-Type: application/json

{
    "nama": "vira eka wahyuni",
    "alamat": "bayat",
    "noHP": "08123456781",
    "tanggal": "2022-08-10",
    "status": "Saudara"
}

###
DELETE http://localhost:3000/api/orang/631aa5b24ec520c8bd8ffbcc
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzMWFhNDM4NGVjNTIwYzhiZDhmZmI5NSIsImVtYWlsIjoidGl0b0BnbWFpbC5jb20iLCJpYXQiOjE2NjI2OTAzNjcsImV4cCI6MTY2Mjc3Njc2N30.gdr-jAWyMaajF_p1oBSIB_FyYBRdJZdeUnYae4Q7ndw
### auth register

POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "nama" : "tito",
    "email" : "tito@gmail.com",
    "password" : "12345"
}

### login
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email" : "tito@gmail.com",
    "password" : "12345"
}



### delete account

DELETE http://localhost:3000/api/account
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzMWFhNzVjNGVjNTIwYzhiZDhmZmJkOCIsImVtYWlsIjoidGl0b0BnbWFpbC5jb20iLCJpYXQiOjE2NjI2OTE1NjMsImV4cCI6MTY2Mjc3Nzk2M30.Bv41lcpWs-7Bnawrx5pSKnkjgYDF16gOkpy2kZfU05Y

### lupa password
POST http://localhost:3000/api/password/forgot
Content-Type: application/json

{
    "email" : "muizzuddin332@gmail.com"
}

### reset password

POST http://localhost:3000/api/password/reset
Content-Type: application/json

{
    "token" : "asdfadsfOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NjcsImVtYWlsIjoibXVpenp1ZGRpbjMzMkBnbWFpbC5jb20iLCJpYXQiOjE2NjE3Nzc2MzN9.ZK9ked-A-aS0Lss1nebTICSxIqojV5MrXPyFM6uWK88",
    "password" : "12345678"
}

### ubah nama
POST http://localhost:3000/api/account
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzMWFhNzVjNGVjNTIwYzhiZDhmZmJkOCIsImVtYWlsIjoidGl0b0BnbWFpbC5jb20iLCJpYXQiOjE2NjI2OTExNjcsImV4cCI6MTY2Mjc3NzU2N30.VErt4u7OF0lMfRft08vFqWhaLFrsBKfHFbDDihXqk-w
Content-Type: application/json

{
    "nama" : "sumarso tito"
}


### motivation
GET http://localhost:3000/api/motivation
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzMWM3ODM3OTk4ZmYyYzhiYWIzZjhjNCIsImlhdCI6MTY2MjgxMDE5NywiZXhwIjoxNjYyODk2NTk3fQ.OVUTL5V6HY2qcYqsW7m_Kuwr-x8XVkdMIN1rzXo2VYY